name: ci

on:
  [push, workflow_dispatch]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: builder1
        uses: docker/setup-buildx-action@v3

      - name: Build against builder1
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.builder1.outputs.name }}
          context: .
          push: false
